FirmarContratoFlask/models/contratos.py
from utils.db import db

class Tipo_Predio(db.Model):
    __tablename__ = 'tipo_predio'
    id_tipo_predio = db.Column(db.Integer(), primary_key = True)
    nomre_predio = db.Column(db.String())      

class Ubigeo(db.Model):
    __tablename__ = 'ubigeo'
    idubigeo = db.Column(db.String(6), primary_key = True)
    departamento = db.Column(db.String(60))
    provincia = db.Column(db.String(60))
    distrito = db.Column(db.String(60))
    superficie = db.Column(db.Float(10,4))
    altitud = db.Column(db.Float(10,4))
    latitud = db.Column(db.Float(10,4))
    longitud = db.Column(db.Float(10,4))

class Predio_Area_Comun(db.Model):
    __tablename__ = 'predio_area_comun'
    id_predio = db.Column(db.Integer(), primary_key = True)
    id_area_comun = db.Column(db.Integer(), primary_key = True)
    codigo = db.Column(db.String(6))
    area = db.Column(db.Float())
    
class Area_Comun(db.Model):
    __tablename__ = 'area_comun'
    id_area_comun = db.Column(db.Integer(), primary_key = True)
    descripcion = db.Column(db.String(50)) 
    
class Predio(db.Model):
    __tablename__ = 'predio' 
    id_predio = db.Column(db.Integer(), primary_key = True)
    id_tipo_predio = db.Column(db.Integer())
    descripcion = db.Column(db.String(80))
    ruc = db.Column(db.String(20))
    telefono = db.Column(db.String(12))
    correo = db.Column(db.String(80))
    direccion = db.Column(db.String(100))
    idubigeo = db.Column(db.String(6))
    
class Servicio(db.Model):
    __tablename__ = 'servicio'
    id_servicio = db.Column(db.Integer(), primary_key = True)
    descripcion = db.Column(db.String(50))

class Solicitud(db.Model):
    __tablename__ = 'solicitud'
    id_solicitud = db.Column(db.Integer(), primary_key = True)
    id_predio = db.Column(db.Integer())
    id_solicitante =  db.Column(db.Integer())
    id_servicio = db.Column(db.Integer())
    area_predio = db.Column(db.Float())
    num_casas = db.Column(db.Integer())
    cant_acomunes = db.Column(db.Integer())
    area_acomunes = db.Column(db.Integer())
    cant_vigilantes = db.Column(db.Integer())
    cant_plimpieza = db.Column(db.Integer())
    fecha_solicitud = db.Column(db.Date())
    
class Solicitud_Cotizacion(db.Model):
    __tablename__ = 'solicitud_cotizacion'
    id_solicitud_cotizacion = db.Column(db.Integer(), primary_key = True)
    id_solicitud = db.Column(db.Integer())
    fecha_cotizacion = db.Column(db.Date())
    id_personal = db.Column(db.Integer())
    importe = db.Column(db.Float(6,2))

class Tipo_Documento(db.Model):
    __tablename__ = 'tipo_documento'
    id_tipo_documento = db.Column(db.Integer(), primary_key = True)
    descripcion = db.Column(db.String(20))
    
class Persona(db.Model):
    __tablename__ = 'persona'
    id_persona = db.Column(db.Integer(), primary_key = True)
    apellido_paterno = db.Column(db.String(60))
    apellido_materno = db.Column(db.String(60))
    nombres = db.Column(db.String(60))
    fecha_nacimiento = db.Column(db.Date())
    id_tipo_documento = db.Column(db.Integer())
    ndocumento = db.Column(db.String(15))
    direccion = db.Column(db.String(150))
    idubigeo = db.Column(db.String(6))

class Rol(db.Model):
    __tablename__ = 'rol'
    id_rol = db.Column(db.Integer(), primary_key = True)
    descripcion = db.Column(db.String(60))
    
class Personal(db.Model):
    __tablename__ = 'personal'
    id_personal = db.Column(db.Integer(), primary_key = True)
    id_persona = db.Column(db.Integer())
    id_rol = db.Column(db.Integer())
    fecha_contrato = db.Column(db.Date())
    fecha_cese = db.Column(db.Date())
    
class Solicitante(db.Model):
    __tablename__ = 'solicitante'
    id_solicitante = db.Column(db.Integer(), primary_key = True)
    id_persona = db.Column(db.Integer())
    id_rol = db.Column(db.Integer())
    telefono = db.Column(db.Integer())
    correo = db.Column(db.String(80))
        
class Contrato(db.Model):
    __tablename__ = 'contrato'
    id_contrato = db.Column(db.Integer(), primary_key=True)
    id_personal = db.Column(db.Integer())
    id_solicitante = db.Column(db.Integer())
    id_solicitud_cotizacion = db.Column(db.Integer())
    fecha_contrato = db.Column(db.Date())
    fecha_firma_solicitante = db.Column(db.Date())
    fecha_firma_personal = db.Column(db.Date())
    fecha_registro = db.Column(db.Date())
    minuta = db.Column(db.String(100))

    def __init__(self, id_personal, id_solicitante, id_solicitud_cotizacion, fecha_contrato, fecha_firma_solicitante, fecha_firma_personal, fecha_registro, minuta):
        self.id_personal = id_personal
        self.id_solicitante = id_solicitante
        self.id_solicitud_cotizacion = id_solicitud_cotizacion
        self.fecha_contrato = fecha_contrato
        self.fecha_firma_solicitante = fecha_firma_solicitante
        self.fecha_firma_personal = fecha_firma_personal
        self.fecha_registro = fecha_registro
        self.minuta = minuta

FirmarContratoFlask/routes/contratos.py
from flask import Blueprint,render_template, request, redirect, url_for, flash, session

from models.contratos import Tipo_Predio
from models.contratos import Ubigeo
from models.contratos import Predio
from models.contratos import Servicio
from models.contratos import Solicitud_Cotizacion
from models.contratos import Solicitud
from models.contratos import Rol
from models.contratos import Tipo_Documento
from models.contratos import Persona
from models.contratos import Personal
from models.contratos import Solicitante
from models.contratos import Contrato

from Google.Carpetas import crear_carpeta

from utils.db import db

contratos = Blueprint("contratos", __name__)


contratos.secret_key = 'clave_secreta'


@contratos.route('/')
def index():
    return render_template('index.html')


@contratos.route('/usuario', methods=['POST'])
def usuario():
    if request.method == 'POST':
        tipo_usuario = request.form['tipo_usuario']
        codigo = request.form['codigo']
    
        if tipo_usuario == 'solicitante':
            
            return redirect(url_for('contratos.pagina_solicitante', codigo=codigo))
        
        elif tipo_usuario == 'contratista':
            
            return redirect(url_for('contratos.pagina_contratista', codigo=codigo))
        
        else:
            return redirect(url_for('index'))   
 

@contratos.route('/solicitante/<codigo>')
def pagina_solicitante(codigo):

    return render_template(
        'solicitante_templates/pagina_solicitante.html', 
        codigo = codigo)
    
  
@contratos.route('/contratista/<codigo>')
def pagina_contratista(codigo):
    return render_template(
        'contratista_templates/pagina_contratista.html', 
        codigo = codigo)  


@contratos.route('/cotizaciones_solicitante/<codigo>', methods=['POST'])
def cotizaciones_solicitante(codigo):
    if request.method == 'POST':
        id_solicitante = int(codigo)
        solicitudes = Solicitud.query.filter_by(Solicitud.id_solicitante == id_solicitante).all()
        cotizaciones = []
        for solicitud in solicitudes:
            cotizacion = Solicitud_Cotizacion.query.filter_by(Solicitud_Cotizacion.id_solicitud == solicitud.id_solicitud).all()
            if cotizacion :
                contrato = Contrato.query.filter_by(Contrato.id_solicitud == solicitud.id_solicitud).all()
                if not contrato:
                    cotizaciones.append(cotizacion)   
        return render_template(
            'solicitante_templates/cotizaciones_solicitante.html', 
            codigo = id_solicitante,
            cotizaciones = cotizaciones)


@contratos.route('/contratos_solicitante/<codigo>', methods=['POST'])
def contratos_solicitante(codigo):
    if request.method == 'POST':
        id_solicitante = int(codigo)
        contratos = Contrato.query.filter_by(Contrato.id_solicitante == id_solicitante).all()
        return render_template(
            'solicitante_templates/contratos_solicitante.html', 
            codigo = id_solicitante,
            contratos = contratos)    

  
@contratos.route('/contratos_contratista/<codigo>', methods=['POST'])
def contratos_contratista(codigo):
    if request.method == 'POST':
        id_personal = int(codigo)
        contratos = Contrato.query.filter_by(
            Contrato.id_personal == id_personal,
            Contrato.fecha_firma_solicitante != None,
        ).all()
        print("CONTRATOS: ",contratos) 
        return render_template(
            'contratista_templates/contratos_contratista.html', 
            codigo = id_personal,
            contratos = contratos)    

 
@contratos.route('/crear_contrato/<id_solicitud>/<codigo>/<id_personal>', methods=['POST'])
def crear_contrato(id_solicitud,codigo,id_personal):
    
    from datetime import datetime
    if request.method == 'POST':
        id_solicitante = int(codigo)
        
        nombre_carpeta = "contrato-"+str(id_solicitud)+"-"+str(id_personal)+"-"+str(id_solicitante)
        
        crear_carpeta(nombre_carpeta)
        
        contrato = Contrato(id_solicitud,
                            id_personal,
                            id_solicitante,
                            datetime.now().date(), 
                            None,
                            None,
                            None,
                            None)
        db.session.add(contrato)
        db.session.commit()
        
        return redirect(url_for('contratos.pagina_solicitante', codigo=id_solicitante))    

@contratos.route('/firmar_contrato_solicitante/<codigo>', methods=['POST'])
def firmar_contrato_solicitante(codigo): 
    id_personal = codigo
    return redirect(url_for('contratos.pagina_solicitante', codigo=id_personal)) 

@contratos.route('/firmar_contrato_contratista/<codigo>', methods=['POST'])
def firmar_contrato_contratista(codigo): 
    id_personal = codigo
    return redirect(url_for('contratos.pagina_contratista', codigo=id_personal)) 

@contratos.route('/descargar_contrato_solicitante/<codigo>', methods=['POST'])
def descargar_contrato_solicitante(codigo): 
    id_personal = codigo
    return redirect(url_for('contratos.pagina_solicitante', codigo=id_personal))   

@contratos.route('/descargar_contrato_contratista/<codigo>', methods=['POST'])
def descargar_contrato_contratista(codigo): 
    id_personal = codigo
    return redirect(url_for('contratos.pagina_contratista', codigo=id_personal))   

FirmarContratoFlask/templates/partials/_bajo_contrato.html
<div class="bajo_contrato">
  <form action="{{url_for('contratos.aceptar_contrato',idminuta=minuta.idminuta)}}" method="POST" enctype="multipart/form-data">   
    <div class="caja_boton">
      <button class="boton">ACEPTAR CONTRATO</button>  
    </div>

    <div class="caja_ingresos">
      <div class="ingresar_firma">
        <label for="image">SUBA SU FIRMA:</label>
        <input
          type="file"
          name="firma"
          accept="firma/png"
          class="form-control-file"
        />
      </div>
  
      <div class="ingresar_huella">
        <label for="image">SUBA SU HUELLA:</label>
        <input
          type="file"
          name="huella"
          accept="huella/png"
          class="form-control-file"
        />
      </div>

    </div>
    
    
  </form>
</div>

FirmarContratoFlask/templates/partials/_contrato.html
<div class="contrato_caja">
  <p class="titulo">
    CONTRATO DE PRESTACION DE<br>
    SERVICIOS DE ADMINISTRACION - CONDOSA<br>
    <br>
  </p>
  <p> 
    Entre la empresa: 
    <input id="nompredio" value="{{predio.nompredio}}"  readonly> ,
  
    representada en este acto por: 
    <input id="nom_completo_solicitante" value="{{solicitante.appaterno}} {{solicitante.apmaterno}}, {{solicitante.nombres}}" readonly> ,
    
    identificado con el DNI: 
    <input id="num_dni_solicitante" value="{{solicitante.numdni}}" readonly> ,
    
    en su carácter de 
    <span class="negrita">PRESIDENTE DE LA JUNTA DE PROPIETARIOS DE</span>
    <input id="nom_predio" value="{{predio.nompredio}}" readonly> ,

    en lo sucesivo 
    <span class="negrita">"LA EMPRESA CONTRATANTE"</span>, 

    y la empresa 
    <span class="negrita">CONDOSA</span>,

    representada en este acto por 
    <input id="nom_completo_contratista" value="{{contratista.appaterno}} {{contratista.apmaterno}}, {{contratista.nombres}}" readonly> ,
    
    identificado con el DNI: 
    <input id="num_dni_contratista" value="{{contratista.numdni}}" readonly> ,

    en su carácter de 
    <span class="negrita">"ENCARGADO DE CONTRATO"</span>, 

    en lo sucesivo 
    <span class="negrita">"LA EMPRESA CONTRATISTA"</span>, 

    se celebra el presente contrato de prestación de servicios administrativos, 
    al tenor de las siguiente cláusulas:
  </p>


  <p>
      <P class="text_ind1">
        1. Teniendo en cuenta la solicitud 
        <input id="id_solicitud" value="{{solicitud.idsolicitud}}" readonly> ,
        realizada el 
        <input id="fechasoli" value="{{solicitud.fechasolicitud}}" readonly> ,
        que contempla la realización de los siguientes servicios:<br>
        <P class="text_ind2">
          1.1. Servicio de Administracion<br>
          1.2. Servicio de Mantenimiento<br>
          1.3. Servicio de Seguridad<br>
        </P>
      </P>

      <P class="text_ind1">
        2. Contando con los siguientes datos:
        <P class="text_ind2">
          2.1. Datos del predio:<br>

          <P class="text_ind3">
            2.1.1. Nombre del predio:
            <input id="nom_predio" value="{{predio.nompredio}}" readonly><br>
            2.1.2. Tipo de predio:
            <input id="tipo_predio" value="{{predio.tipo}}" readonly><br>
            2.1.3. Area del predio:
            <input id="area_predio" value="{{predio.area}} m2" readonly><br>
            2.1.4. Numero de accesos:
            <input id="accesos_predio" value="{{predio.numaccesos}}" readonly><br>
            2.1.5. Numero de casas:
            <input id="casas_predio" value="{{predio.numcasas}}" readonly><br>
            2.1.6. Dimension de las areas comunes:
            <input id="comunes_predio" value="{{predio.dimareascomm}} m2" readonly><br>
            2.1.7. Presentando ciertas caracteristicas como:
            <textarea readonly class="custom-textarea" >
              {{predio.caracsiyse }}
            </textarea><br>
          </P>
        </P>

        <p class="text_ind2">
          2.2. Datos de personal:<br>

          <P class="text_ind3">
            <div class="caja_tabla">
              <table class="table_trabajadores">
                            
                <tr class="table_head">
                  <th class="idtrabajador">
                      CODIGO
                  </th>
                  <th class="appaterno">
                      AP. PATERNO
                  </th>
                  <th class="apmaterno">
                      AP. MATERNO
                  </th>
                  <th class="nombres">
                      NOMBRES
                  </th>
                </tr>
  
                {% for trabajador in trabajadores %}
                  <tr class="table_row " >
                      <td class="id_col">
                          {{ trabajador.idtrabajador}}
                      </td>
                      <td class="appater_col">
                          {{ trabajador.appaterno}}
                      </td>
                      <td class="apmater_col">
                          {{ trabajador.apmaterno}}
                      </td >
                      <td class="nombres_col">
                          {{ trabajador.nombres}}
                      </td>
                  </tr>    
                {% endfor %}
              </table>
            </div>
          </P>
        </p>
      </P>

      <P class="text_ind1">
        3. Aceptando la cotizacion por el valor de
        <input id="cotizacion" value="S/.{{cotizacion.monto}}" readonly> ,
        realizada y, teniendo en cuenta que el contrato tenda una duracion que va
        desde el
        <input id="inicio" value="{{solicitud.fechainicioservicio}}" readonly> ,
        hasta el 
        <input id="fin" value="{{solicitud.fechafinservicio}}" readonly> ,
        y aceptando los
        <span class="negrita">TERMINOS Y CONDICIONES</span>
        expecificados por la empresa 
        <span class="negrita">CONDOSA</span>,
      </P>
  </p>



  <script>
    window.addEventListener('DOMContentLoaded', () => {
      const inputs = document.querySelectorAll('input[readonly]');
      inputs.forEach(input => {
        input.style.width = (input.value.length+1) + 'ch';
      });
    });
  </script>
    
  
</div>

FirmarContratoFlask/templates/partials/_ingreso_usuario.html
<div class = "ingreso_usuario" >
    <form action="/usuario" method="POST">
        <p class="titulo">
            TIPO DE USUARIO
        </p>
        <div class="mb-3">
            <label for="fullname" style="font-weight: bold;">ESCRIBA SU ROL:</label>
            <input type="text" id="tipo_usuario" name="tipo_usuario" required>
        </div>
        
        <div class="mb-3">
            <label for="fullname" style="font-weight: bold;">ESCRIBA SU CODIGO:</label>
            <input type="text" id="codigo" name="codigo" required>
        </div>
        <button type="submit" class="btn btn-dark btn-sm rounded-0">INGRESAR</button>
    </form>
</div>

FirmarContratoFlask/templates/partials/_message.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-info alert-dismissible fade show {% if message == 'CONTRATO FIRMADO CORRECTAMENTE' %}alert-success{% else %}alert-danger{% endif %}" role="alert">
        {{ message }}
        {% if message == 'CONTRATO FIRMADO CORRECTAMENTE' %}
          <button style="background: rgb(153, 230, 146)" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {% else %}
          <button style="background: rgb(206, 82, 33)" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {% endif %}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

<script>
  setTimeout(function() {
    var alertElement = document.querySelector('.alert');
    var closeButton = alertElement.querySelector('.btn-close');
    closeButton.click();
  }, 3000);
</script>

FirmarContratoFlask/templates/partials/_navbar1.html
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/">CONDOSA</a>
  </div>
</nav>

FirmarContratoFlask/templates/partials/_navbar2.html
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand" href="/">CONDOSA</a>
    
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">FIRMAR CONTRATO</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  

FirmarContratoFlask/templates/partials/_tabla_contratos_contratista.html
<div class = "caja_tabla_util">
    <table class="tabla_contratos_contratista">
        <tr class="tabla_head">
            <th class="col_cab1">
                ID
            </th>
            <th class="col_cab1">
                SOLICITANTE
            </th>
            <th class="col_cab1">
                F. FIR. SOLI.
            </th>
            <th class="col_cab1">
                F. REGISTRO
            </th>
            <th class="col_cab1">
                OPCION
            </th>
        </tr>
        {% for contrato in contratos %}
            <tr class="tabla_row " >
                <td class="col_row1">
                    {{contrato.id_contrato}}
                </td>
                <td class="col_row1">
                    {{contrato.id_personal}}
                </td>
                <td class="col_row1">
                    {{contrato.fecha_contrato}}
                </td >
                <td class="col_row1">
                    {{contrato.fecha_registro}}
                </td >
                <td class="col_row2">
                    {% if contrato.fecha_firma_personal is none %}
                            <form 
                            action="{{url_for('contratos.firmar_contrato_contratista',codigo=codigo)}}" 
                            method="POST" 
                            style="display: inline;">
                            <button type="submit" class="btn btn-dark btn-sm rounded-0">FIRMAR</button>
                        </form>
                    {% else %}
                        <form 
                            action="{{url_for('contratos.descargar_contrato_contratista',codigo=codigo)}}" 
                            method="POST" 
                            style="display: inline;">
                            <button type="submit" class="btn btn-dark btn-sm rounded-0">DESCARGAR</button>
                        </form>
                    {% endif %} 
                </td>
            </tr>  
        {% endfor %}
    </table>
</div>

FirmarContratoFlask/templates/partials/_tabla_contratos_solicitante.html
<div class = "caja_tabla_util">
    <table class="tabla_contratos_solicitante">
        <tr class="tabla_head">
            <th class="col_cab1">
                ID
            </th>
            <th class="col_cab1">
                CONTRATISTA
            </th>
            <th class="col_cab1">
                F. CREACION
            </th>
            <th class="col_cab1">
                F. REGISTRO
            </th>
            <th class="col_cab1">
                CONTRATO
            </th>
        </tr>
        {% for contrato in contratos %}
            <tr class="tabla_row " >
                <td class="col_row1">
                    {{contrato.id_contrato}}
                </td>
                <td class="col_row1">
                    {{contrato.id_personal}}
                </td>
                <td class="col_row1">
                    {{contrato.fecha_contrato}}
                </td >
                <td class="col_row1">
                    {{contrato.fecha_registro}}
                </td >
                <td class="col_row2">
                    {% if contrato.fecha_firma_solicitante is none %}
                        <form 
                            action="{{url_for('contratos.firmar_contrato_solicitante',codigo=codigo)}}" 
                            method="POST" 
                            style="display: inline;">
                            <button type="submit" class="btn btn-dark btn-sm rounded-0">FIRMAR</button>
                        </form>
                    {% else %}
                        <form 
                            action="{{url_for('contratos.descargar_contrato_solicitante',codigo=codigo)}}" 
                            method="POST" 
                            style="display: inline;">
                            <button type="submit" class="btn btn-dark btn-sm rounded-0">DESCARGAR</button>
                        </form>
                    {% endif %} 
                </td>  
            </tr> 
        {% endfor %}  
    </table>
</div>

FirmarContratoFlask/templates/partials/_tabla_cotizaciones_solicitante.html
<div class = "caja_tabla_util">
    <table class="tabla_cotizaciones_solicitante">
        <tr class="tabla_head">
            <th class="col_cab1">
                ID
            </th>
            <th class="col_cab1">
                CONTRATISTA
            </th>
            <th class="col_cab1">
                FECHA
            </th>
            <th class="col_cab1">
                IMPORTE
            </th>
            <th class="col_cab1">
                CONTRATO
            </th>
        </tr>
        {% for cotizacion in cotizaciones %}
            <tr class="tabla_row " >
                <td class="col_row1">
                    {{cotizacion.id_solicitud}}
                </td>
                <td class="col_row1">
                    {{cotizacion.id_personal}}
                </td>
                <td class="col_row1">
                    {{cotizacion.fecha_cotizacion}}
                </td>
                <td class="col_row1">
                    {{cotizacion.importe}}
                </td>
                <td class="col_row2">
                    <form 
                        action="{{url_for('contratos.crear_contrato',id_solicitud = cotizacion.id_solicitud,codigo=codigo,id_personal=cotizacion.id_personal)}}" 
                        method="POST" 
                        style="display: inline;">
                        <button type="submit" class="btn btn-dark btn-sm rounded-0">CREAR</button>
                    </form>
                </td>
            </tr> 
        {% endfor %}
    </table>
</div>
   